---
- hosts: events
  remote_user: vagrant
  vars:
    remote_user: vagrant
    project_name: normalize_events
    installed_dir: "/var/www/{{ project_name }}"
    repo: git@github.com:adamyala/normalize_events.git
    branch: devops
    psql_password: password

  tasks: 
  - name: update package cache and upgrade packages
    apt: 
      update_cache: yes
      upgrade: full
    become: true
    become_user: root

  - name: install ubuntu packages
    apt: 
      name: "{{ item }}"
      state: latest
    with_items:
      - apache2
      - libapache2-mod-wsgi-py3
      - git
      - python3-dev
      - python-pip
      - postgresql
      - python-psycopg2
      - libpq-dev
    become: true
    become_user: root

  - name: change owner to {{ remote_user }}
    file:
      owner: "{{ remote_user }}"
      path: "/var/www/"
      state: directory
    become: true
    become_user: root

  - name: download repo
    git:
      accept_hostkey: true
      repo: "{{ repo }}"
      dest: "{{ installed_dir }}"
      version: "{{ branch }}"

  - name: copy config file
    template:
      src: "../{{ project_name }}/config.py"
      dest: "{{ installed_dir }}/{{ project_name }}/config.py"
    become: true
    become_user: root

  - name: install virtualenv
    pip:
      virtualenv_python: python3
      name: virtualenv
      state: latest
    become: true
    become_user: root

  - name: install dependancies
    pip:
      virtualenv_python: python3
      virtualenv: "{{ installed_dir }}/venv/bin/python"
      requirements: "{{ installed_dir }}/requirements.txt"

  - name: make events database
    postgresql_db:
      name: events
    become: true
    become_user: postgres

  - name: make {{ remote_user }} and wwwdata postgresql users
    postgresql_user:
      db: events
      name: "{{ item }}"
      password: "{{ psql_password }}"
      state: present
    with_items:
      - "{{ remote_user }}"
      - wwwdata
    become: true
    become_user: postgres

  - name: seed database
    command: "../venv/bin/python/bin/python seed_db.py"
    args:
      chdir: "{{ installed_dir }}/normalize_events"

  - name: add db user privlages
    postgresql_user:
      db: events
      name: "{{ item[0] }}"
      password: "{{ psql_password }}"
      priv: "{{ item[1] }}"
      state: present
    with_nested:
      - [ "{{ remote_user }}", wwwdata" ]
      - [ 'event:ALL', 'category:ALL', 'eventcategory:ALL', 'eventlog:ALL' ]
    become: true
    become_user: postgres

  - name: copy apache config
    template: src=files/000-default.conf dest=/etc/apache2/sites-available/000-default.conf
    become: true
    become_user: root
    notify: restart apache

  handlers:
    - name: restart apache
      action: service name=apache2 state=restarted
      become: true
      become_user: root
