---
- hosts: events
  become: true
  become_user: root
  vars:
    project_name: normalize_events
    repo: git@github.com:adamyala/normalize_events.git
    branch: devops

  pre_tasks:
    - name: install ubuntu packages
      apt: 
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - libpq-dev

  roles:
    - role: python

    - role: postgres
      postgresql_version: 9.5
      postgresql_admin_user: postgres
      postgresql_default_auth_method: "trust"
      postgresql_databases:
      - name: events
      postgresql_users:
        - name: www-data

    - role: uwsgi-emperor

    - role: uwsgi-vassal
      python_version: 3.5
      app_name: "{{ project_name }}"
      app_enabled: yes
      requirements_file: "/www/{{ project_name }}/requirements.txt"
      system_packages:
        - python3-dev
      uwsgi:
        wsgi-file: __init__.py
        callable: app
        socket: 127.0.0.1:5000
        workers: 1
        buffer-size: 16384
        pythonpath: "/www/{{ project_name }}/{{ project_name }}"
        chdir: "/www/{{ project_name }}/{{ project_name }}"
        home: "/var/venvs/{{ project_name }}"

    - role: nginx
      nginx_user: 'www-data'
      nginx_sites:
        normalize_events:
          - listen 80
          - server_name 127.0.0.1
          - charset utf-8
          - root www/{{ project_name }}
          - gzip on
          - gzip_proxied any
          - gzip_types text/plain text/xml application/json text/html
          - gzip_vary on
          - gzip_disable "MSIE [1-6]\.(?!.*SV1)"
          - location @app { uwsgi_pass 127.0.0.1:5000; include uwsgi_params; }
          - location / { try_files $uri @app; }

  tasks: 
  - name: seed database categories
    command: "/var/venvs/normalize_events/bin/python /www/normalize_events/normalize_events/seed_db.py"
    become: true
    become_user: www-data

  - name: get events
    command: "/var/venvs/normalize_events/bin/python /www/normalize_events/normalize_events/pop_db.py"
    become: true
    become_user: www-data